---
- name: initialize docker with wifi interface
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{swarm_network_interface}}"

- name: create docker network
  community.docker.docker_network:
    name: "{{ item }}"
    state: present
  with_items:
    - nextcloud
    - plex
    - redmine
    - wireguard
    - traefik

- name: replace the nextcloud db password to random
  replace:
    path: /home/{{ ansible_user }}/PersonalServer/nextcloud/db.env
    regexp: 'POSTGRES_PASSWORD=.*'
    replace: 'POSTGRES_PASSWORD={{ lookup("password", "/dev/null length=32 chars=ascii_letters,digits") }}'

- name: replace redmine db username and password with randomized password
  replace:
    path: /home/{{ ansible_user }}/PersonalServer/redmine/docker-compose.yml
    regexp: '{{ item }}=.*'
    replace: '{{ item }}={{ lookup("password", "/dev/null length=32 chars=ascii_letters,digits") }}'
  with_items: 
    - POSTGRES_USER
    - POSTGRES_PASSWORD

- name: replace username and password for samba
  replace:
    path: /home/{{ ansible_user }}/PersonalServer/samba/docker-compose.yml
    regexp: "USER"
    replace: "{{ SAMBA_USER }}"
  with_items: 
    - { regex:"USER", replace: "{{ SAMBA_USER }}" }
    - { regex:"PASSWORD", replace: "{{ SAMBA_PASSWORD }}" }
    - { regex:"SAMBA_NAME", replace: "{{ SAMBA_NAME }}" }

- name: create wireguard directory for config
  file:
    path: "{{ ansible_user }}/wireguard/appdata"
    state: directory
    mode: 0755

- name: run composes
  shell: |
    docker compose -f /home/{{ ansible_user }}/PersonalServer/{{ item }}/docker-compose.yml up -d
  with_items: 
    - nextcloud
    - plex
    - redmine
    - wireguard





