---
- name: initialize docker with wifi interface
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{swarm_network_interface}}"
  when: ansible_hostname == "master"

- name: create docker network
  community.docker.docker_network:
    name: "{{ item }}"
    state: present
  with_items:
    - nextcloud
    - plex
    - redmine
    - wireguard
    - traefik
  when: ansible_hostname == "master"

- name: build docker compose file
  community.docker.docker_compose:
    project_src: "/home/{{ ansible_user }}/PersonalServer/{{ item }}"
    build: yes
    state: present
    files:
      - docker-compose.yml
  with_items: 
    - nextcloud
    - plex
    - redmine
    - wireguard
  when: ansible_hostname == "master"




