- name: move ssh key to ssh folder
  copy:
    src: "{{ item.key }}"
    dest: "/home/{{ ansible_user }}/.ssh/{{ item.destination }}"
    owner: "pi"
    group: "pi"
    mode: "{{ item.mode }}"
  with_items: 
    - { key: "keyfile.key", destination: "pi", mode: "0600" }
    - { key: "pubkey.key", destination: "pi.pub",mode: "0644" }

- name: add ssh config file with config
  copy:
    src: config
    dest: /home/{{ ansible_user }}/.ssh/config
    mode: 0644

- name: get deployment file from github account
  block:
  - name: clone repo
    git:
      repo: git@github.com:rection/PersonalServer.git
      dest: /home/{{ ansible_user }}/PersonalServer
      version: main
      force: yes
      update: yes
      accept_hostkey: yes
      key_file: /home/{{ ansible_user }}/.ssh/pi

  - name: run docker-compose
    include_tasks: build.yml
  when: ansible_hostname == "master"