- name: install docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: add docker keyring
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: apt update and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: install docker-ce
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
