- name: remove source file in apt sources
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: install docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: add docker keyring
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: get system architecture 
  shell: dpkg --print-architecture
  register: system_architecture

- name: add docker repository
  apt_repository:
    repo: "deb [arch={{system_architecture.stdout}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 3600

- name: apt update and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: install docker-ce
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
