- name: if docker binary installed then skip
  stat:
    path: /usr/bin/docker
  register: docker_binary
  changed_when: false
  failed_when: false

- name: block for install docker
  block:
  - name: install docker
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  - name: create keyrings directory
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: 0755

  - name: add docker keyring
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
      keyring: /etc/apt/keyrings/docker.gpg
    changed_when: false

  - name: get system architecture 
    shell: dpkg --print-architecture
    register: system_architecture
    changed_when: false
    failed_when: false

  - name: add docker repository
    apt_repository:
      repo: "deb [arch={{system_architecture.stdout}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Reboot a slow machine that might have lots of updates to apply
    ansible.builtin.reboot:
      reboot_timeout: 3600

  - name: apt update and upgrade
    apt:
      update_cache: yes
      upgrade: yes

  - name: install docker-ce
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

  - name: add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  when: not docker_binary.stat.exists