- name: update and upgrade system packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: install development packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - git
    - ansible
    - python3-pip

- name: install python packages
  become_user: pi
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - pip
    - docker
